### PR TITLE
New method to return http response

### PR DESCRIPTION
**Pull request by abdelrahmanbadr**
Sometimes you will need the response to fire the next test function
So it's better to return the response from Done method

### CODE REVIEW

**Comment by h2non** [comment]
What about a new exported method that returns the response instance, such as `mock.Response()`?

My only objection is that the current implementation would introduce a breaking change and major version bump would be needed?

**Comment by abdelrahmanbadr** [comment]
I understand your objection  and i modified the code to add new method

**Comment by h2non** [comment]
Thanks. I'm thinking that `.Send()` or `.Test()` methods could be semantically better and shorten for this purpose and still evidence the interface change and purpose. Thoughts?

**Comment by abdelrahmanbadr** [comment]
I didn't get your point !

**Comment by h2non** [comment]
> you mean method name better to be .Send() or .Test() ?

Yeah, it would be more explicit about the action performed, but also returning the response object as part of the return contract.

**Comment by abdelrahmanbadr** [comment]
`returning the response object as part of the return contract`
I don't know which contract you mean to return the response object with.
But I think it will be more clear to return response object it self from this method, to make it simple to use it when calling this method, Any thoughts?

**Comment by h2non** [comment]
That's all I was looking for. Thanks!

**Comment by abdelrahmanbadr** [comment]
Thanks

**Comment by h2non** [comment]
New version `v3.0.1` is now available:
https://github.com/h2non/baloo/releases/tag/v3.0.1

Upgrade local package:
```go
$ go get -u gopkg.in/h2non/baloo.v3
```

**Pull request merged**
